// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRMBackend.Entities;

#nullable disable

namespace SRMBackend.Migrations
{
    [DbContext(typeof(ScholarshipDbContext))]
    partial class ScholarshipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRMBackend.Entities.Campus", b =>
                {
                    b.Property<string>("CampusId")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("campus_id");

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("campus_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.HasKey("CampusId")
                        .HasName("campus_pkey");

                    b.ToTable("campus", "scholarship");
                });

            modelBuilder.Entity("SRMBackend.Entities.Faculty", b =>
                {
                    b.Property<string>("FacId")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("fac_id");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("campus_id");

                    b.Property<string>("FacNameTh")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fac_name_th");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.HasKey("FacId")
                        .HasName("faculty_pkey");

                    b.HasIndex("CampusId");

                    b.ToTable("faculty", "scholarship");
                });

            modelBuilder.Entity("SRMBackend.Entities.Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_salt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("members_pkey");

                    b.HasIndex(new[] { "Email" }, "members_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "members_username_key")
                        .IsUnique();

                    b.ToTable("members", "scholarship");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "admin@psu.ac.th",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "7903CC6982F0385E1000F276B60E109E6AA9D5AAE9A88E4444FA8C9FF5D59F60",
                            PasswordSalt = "FB0BB1412C716BE31CFDD0F7EACC7DE3",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SRMBackend.Entities.PdpaConsent", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VersionId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PdpaText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pdpa_text");

                    b.HasKey("VersionId")
                        .HasName("pdpa_consent_pkey");

                    b.ToTable("pdpa_consent", "scholarship");
                });

            modelBuilder.Entity("SRMBackend.Entities.ScholarshipRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("DeptName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dept_name");

                    b.Property<string>("FacId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("fac_id");

                    b.Property<decimal>("Gpax")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("gpax");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("grade_level");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_delete");

                    b.Property<int>("PdpaConsentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("pdpa_consent_version");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("request_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RequestReason")
                        .HasColumnType("text")
                        .HasColumnName("request_reason");

                    b.Property<decimal>("RequestedAmount")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("requested_amount");

                    b.Property<int>("ScholarshipTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("scholarship_type_id");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("student_email");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("student_id");

                    b.Property<string>("StudentLname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("student_lname");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("student_name");

                    b.HasKey("RequestId")
                        .HasName("scholarship_request_pkey");

                    b.HasIndex("FacId");

                    b.HasIndex("PdpaConsentVersion");

                    b.HasIndex("ScholarshipTypeId");

                    b.ToTable("scholarship_request", "scholarship");
                });

            modelBuilder.Entity("SRMBackend.Entities.ScholarshipStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("scholarship_status_pkey");

                    b.ToTable("scholarship_status", "scholarship");
                });

            modelBuilder.Entity("SRMBackend.Entities.ScholarshipTypes", b =>
                {
                    b.Property<int>("SholarshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sholarship_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SholarshipId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("SholarshipName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sholarship_name");

                    b.HasKey("SholarshipId")
                        .HasName("scholarship_types_pkey");

                    b.ToTable("scholarship_types", "scholarship");
                });

            modelBuilder.Entity("SRMBackend.Entities.Faculty", b =>
                {
                    b.HasOne("SRMBackend.Entities.Campus", "Campus")
                        .WithMany("Faculty")
                        .HasForeignKey("CampusId")
                        .IsRequired()
                        .HasConstraintName("fk_campus_id");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("SRMBackend.Entities.ScholarshipRequest", b =>
                {
                    b.HasOne("SRMBackend.Entities.Faculty", "Fac")
                        .WithMany("ScholarshipRequest")
                        .HasForeignKey("FacId")
                        .IsRequired()
                        .HasConstraintName("fk_fac_id");

                    b.HasOne("SRMBackend.Entities.PdpaConsent", "PdpaConsentVersionNavigation")
                        .WithMany("ScholarshipRequest")
                        .HasForeignKey("PdpaConsentVersion")
                        .IsRequired()
                        .HasConstraintName("fk_pdpa_consent");

                    b.HasOne("SRMBackend.Entities.ScholarshipTypes", "ScholarshipType")
                        .WithMany("ScholarshipRequest")
                        .HasForeignKey("ScholarshipTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_scholarshipe_type_id");

                    b.Navigation("Fac");

                    b.Navigation("PdpaConsentVersionNavigation");

                    b.Navigation("ScholarshipType");
                });

            modelBuilder.Entity("SRMBackend.Entities.Campus", b =>
                {
                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("SRMBackend.Entities.Faculty", b =>
                {
                    b.Navigation("ScholarshipRequest");
                });

            modelBuilder.Entity("SRMBackend.Entities.PdpaConsent", b =>
                {
                    b.Navigation("ScholarshipRequest");
                });

            modelBuilder.Entity("SRMBackend.Entities.ScholarshipTypes", b =>
                {
                    b.Navigation("ScholarshipRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
